project1/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('todo.urls'))
] 
# + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

todo/urls.py
from django.urls import path, include
from . import views

app_name = "todo"

urlpatterns = [
     path('', views.home, name='home'),
     path('del/<int:id>', views.delete_task, name='delete_task'),
]

todo/models.py
from django.db import models

# Create your models here.
class Tarefa(models.Model):
    nome = models.CharField('nova tarefa',max_length=200)
    data = models.DateTimeField(auto_now_add=True)
    
    def __str__(self) -> str:
        return self.nome

todo/forms.py
from django import forms
from .models import Tarefa

class TarefaForm(forms.ModelForm):
    class Meta:
        model = Tarefa
        fields = "__all__"
        
        widgets = {}
        
        widgets = {
            'nome': forms.TextInput(attrs={'placeholder':'tarefa...'}),
        }
    
    

todo/views.py
from django.shortcuts import render,redirect
from .models import Tarefa
from .forms import TarefaForm

# Create your views here.
def home(request):
    if request.method=="GET":
        tarefas = Tarefa.objects.all()
        formulario = TarefaForm()
    elif request.method=="POST":
        formulario = TarefaForm(request.POST)
        if formulario.is_valid():
            formulario.save()
            return redirect("todo:home")
    return render(request, 'todo/home.html',{'tarefas':tarefas,"formulario":formulario})

def delete_task(request, id):
    tarefa = Tarefa.objects.filter(pk=id)
    tarefa.delete()    
    return redirect("todo:home")

todo/templates/todo/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <title>TodoApp</title>
</head>

<body>
    <div class="container">
        <h1 class="mt-5 mb-5">Lista de Tarefas</h1>
        {% block conteudo %}


        {% endblock %}
    </div>
</body>

</html>

todo/templates/todo/home.html
{% extends 'todo/base.html' %}
{% load static %}
{% block conteudo %}

  <form action="" method="post">

    {% csrf_token %}
<!-- 
    {{formulario.as_p}}
    <button class="btn btn-primary">adicionar</button>

    <hr> -->
    <div class="row">
        <div class="col">
          <input type="text" class="form-control" placeholder="nova tarefa.." name="nome">
        </div>
        <div class="col">
           <button class="btn btn-primary">adicionar</button>
        </div>
     </div>


  </form>

  {% for tarefa in tarefas %}

  <p>{{ forloop.counter }} - {{ tarefa.nome}} 
     <a href="{% url 'todo:delete_task' tarefa.id %}">
        <img src="{% static 'x-circle.svg' %}" class="icon">
     </a>

  </p>
     
  {% endfor %}

{% endblock %}